services:
  gateway:
    image: ghcr.io/microservices-benchmarking-11-kiop-2023/java-mono:latest
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - JAVA_OPTS=-Xmx1024m
    ports:
      - "5000:8080"